spring:
  application:
    name: Configuration

  h2:
   console:
     enabled: true
     path: /h2-console #http://localhost:8080/h2-console

logging:
   level:
     root: INFO
     com:
       intheeast:
         demo: INFO
     org:
       hibernate:
         SQL: DEBUG
         orm:
           jdbc:
             bind: TRACE
  
      
  